name: .NET Full Framework - Nuget Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  build:
    runs-on: windows-latest  
    steps:
      # Checks-out repository
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1
      # Execute psake build with argument ()
      - name: Execute psake build
#        env: 
#          NUGET_APIKEY: ${{ secrets.AZ_VAULT_ACCESS_CLIENT_ID }}
#          MYGET_APIKEY: ${{ secrets.AZ_VAULT_ACCESS_CLIENT_SECRET }}
        shell: cmd
        run: |
          build.cmd cipk
