name: .NET Full Framework - Nuget Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  build:
    runs-on: windows-latest  
    steps:
      # Checks-out repository
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
          fetch-depth: 1
      # Execute psake build with argument ()
      - uses: numworks/setup-msys2@v1
      - run: msys2do build.cmd cipk
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true