name: .NET Full Framework - Nuget Package

on:
  push:
    branches:    
      - feature/**
    
jobs:

  build:
    runs-on: windows-latest  
    steps:
      # Checks-out repository
      - uses: actions/checkout@v1
      # Execute psake build script
      - name: Execute psake build with argument (cipk)
        shell: cmd
        run: |
          build.cmd cipk
        
        